---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # renovate: datasource=pypi depName=ruff
    rev: v0.1.14
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
