---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/RobertCraigie/pyright-python
    # renovate: datasource=github-releases depName=pyright-python
    rev: v1.1.338
    hooks:
      - id: pyright
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # renovate: datasource=pypi depName=ruff
    rev: v0.1.6
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
