---
name: Lint

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
      - "v**"
  pull_request:
    branches:
      - "main"
      - "v**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: earthly/actions-setup@v1.0.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # renovate: datasource=docker depName=earthly/earthly
          version: "v0.7.22"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Run Earthly Lint
        env:
          EARTHLY_CI: true
        run: earthly +lint
      - uses: "pre-commit/action@v3.0.0"
